### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by InfamousPlatypus** [Spooky-Manufacturing/8Q#19]
**Did you search the [F.A.Q.]() First?**
Yes
**What is your question?**
Is there a mapping of what qbits are connected? I don't remember seeing any at all and I can't tell from the circuit drawings.

**Comment by NoahGWood** [comment]
At one point I had a relatively complete architecture document, that was one of the victims of the drive failure. The general architecture of this design has four qubits on either side, these are independent of one another, and then we have the gates in the middle which enable you to actually do various controlled logic on two qubits.

All of the qubits can be entangled by using the control circuitry labelled in qpio.sch to shift them into the controlled gate where the non-linearity occurs:
![qpio](https://user-images.githubusercontent.com/26890744/153282349-f72edc89-18c0-425d-8cf2-c559099aa187.png)

It works much the same way as a regular processor instruction bus, you send it commands to control the state of the circuit. so to run qasm like:
```
qubit q1 = 0;
qubit q7 = 1;
CX q1, q7;
MEASURE;
```
Your compiler would turn that into binary instructions like:
```
1. Reset everything:    00000000000000000000000000000000000000000000000000000000000000000000000000000
2. Set Q7 to 1:         00000000000000000000000000000000000000000000000000000010000000000000000000000
3. Set operation to CX: 00000000000001000000000000000000000000000000000000000010000001000000000000000
4. Run operation:       00000100000001000000000000000000000000000000000000000110000001000000000000000
5. Measure QRAM:        10000100001000000000000000000000000000000000000000000000001001000000000000001
```
When I first wrote the architecture I had an excel spreadsheet that listed every possible command and the required bits to perform it, I'll see if I can't put another together for you here in the next week or so.

**Comment by InfamousPlatypus** [comment]
All right, thank you. All qbits can be entangled with all other qbits.
